"""Create .env on first run, and top it up on later ones.

Written as a script rather than shell in the Makefile because it has to do two
different things: generate secrets for a fresh install, and add only the keys a
newer version introduced to an existing one. Regenerating the file wholesale
would change POSTGRES_PASSWORD, which an already initialised database would then
refuse.
"""

import secrets
import socket
from pathlib import Path

ENV_FILE = Path(".env")
HEADER = "# Generated by 'make up'. Keep it: the secrets live only here.\n"


def free_port(start: int, span: int = 50) -> int:
    for port in range(start, start + span):
        with socket.socket() as probe:
            if probe.connect_ex(("127.0.0.1", port)) != 0:
                return port

    raise SystemExit(f"No free port between {start} and {start + span}")


def read_existing() -> dict:
    if not ENV_FILE.is_file():
        return {}

    values = {}
    for line in ENV_FILE.read_text().splitlines():
        if line.strip() and not line.lstrip().startswith("#") and "=" in line:
            key, _, value = line.partition("=")
            values[key.strip()] = value
    return values


def main() -> None:
    existing = read_existing()

    defaults = {
        "BIND_ADDRESS": lambda: "127.0.0.1",
        "POSTGRES_DB": lambda: "fwtrack",
        "POSTGRES_USER": lambda: "fwtrack",
        "POSTGRES_PASSWORD": lambda: secrets.token_urlsafe(18),
        "POSTGRES_PORT": lambda: str(free_port(5432)),
        "GRAFANA_ADMIN_PASSWORD": lambda: secrets.token_urlsafe(18),
        "GRAFANA_PORT": lambda: str(free_port(3000)),
        "FWTRACK_INGEST_TOKEN": lambda: secrets.token_urlsafe(32),
        "INGEST_PORT": lambda: str(free_port(8099)),
    }

    added = {}
    for key, make in defaults.items():
        if key not in existing:
            added[key] = make()

    # Derived from the values above, so it is only written when absent and
    # always matches whatever password the database was initialised with.
    settings = {**existing, **added}
    if "FWTRACK_DSN" not in settings:
        added["FWTRACK_DSN"] = (
            f"postgresql://{settings['POSTGRES_USER']}:{settings['POSTGRES_PASSWORD']}"
            f"@localhost:{settings['POSTGRES_PORT']}/{settings['POSTGRES_DB']}"
        )

    if not added:
        print("Keeping the existing .env")
        return

    if existing:
        with ENV_FILE.open("a", encoding="utf-8") as f:
            f.write("\n" + "".join(f"{k}={v}\n" for k, v in added.items()))
        print(f"Added to .env: {', '.join(added)}")
    else:
        ENV_FILE.write_text(HEADER + "".join(f"{k}={v}\n" for k, v in added.items()))
        ENV_FILE.chmod(0o600)
        print(
            f"Generated .env (postgres {added['POSTGRES_PORT']}, "
            f"grafana {added['GRAFANA_PORT']}, ingest {added['INGEST_PORT']})"
        )


if __name__ == "__main__":
    main()
